### ISSUE TITLE
Waterskin Diary

### ISSUE THREAD

**Issue by Kendall924** [dot2JC/GIMP#14]
![image](https://user-images.githubusercontent.com/93501180/143264472-47727d4a-5345-45ea-bad6-eed9042f12ed.png)
not really an issue but maybe add one waterskin to the items grabbed. since you have an axe, while doing the warbler you can cut a cactus for water for another diary task.

**Comment by dot2JC** [comment]
In my opinion, it's implied you already have this as you should have accomplished it during Tourist Trap in section [Al-Kharid and Port Khazard](https://dot2jc.github.io/GIMP/#Desert1) since the quest guide recommends you bring a few, but I could see reason for adding a something along the lines of "if you didn't do it earlier...".

**Comment by dot2JC** [comment]
Fixed in commit a51f3ec
